# classical model: [LogReg, NCM, LogReg, NCM, RandomForest, 
#                   xgboost, catboost, lightgbm, svm, knn, 
#                   NaiveBayes, dummy, LinearRegression]
# deep_model:      [mlp, resnet, ftt, node, autoint, tabpfn, 
#                   tangos, saint, tabcaps, tabnet, snn, ptarl, 
#                   danets, dcn2, tabtransformer, dnnr, switchtab, 
#                   grownet, tabr, modernNCA, hyperfast, bishop, 
#                   realmlp, protogate, mlp_plr, excelformer, grande,
#                   amformer, tabptm, trompt, tabm, PFN-v2, t2gformer]
# --------------------------------------------------------------------------------
# model constraints:
# ------ dataset constraints ------
# - classification only: [tabpfn, ncm, protogate, tabcaps]
# ------ cat policy ------
# - better not with cat_indice: [classical model, danets, dnnr, excelformer, mlp, node, protogate,
#                                resnet, switchtab, tabcaps, tabnet, tangos]
# - better with cat_indice: [tabpfn, PFN-v2, realmlp, catboost, tabtransformer,
#                            amformer, autoint, bishop, dcn2, ftt, grande, 
#                            grownet, hyperfast, ptarl, saint, snn, t2gformer,
#                            tabm, trompt]
# - use tabr_ohe: [mlp_plr, modernNCA, tabr]
# - use ohe: [tabptm]
# ------ num policy ------
# - better not with num_binning: [tabpfn, PFN-v2, hyperfast, modernNCA, tabptm, tabr]
# ------ norm policy ------
# - better not with norm: [tabpfn, PFN-v2, hyperfast]
# - standard norm: [tabptm]
# --------------------------------------------------------------------------------
# regression dataset: [cpu_small]
# classification dataset: [bank]
# --------------------------------------------------------------------------------
dataset:
  # - ASP-POTASSCO-classification
  # - Amazon_employee_access
  # - Ailerons
  # - BNG(tic-tac-toe)
  # - Bias_correction_r_2
  # - Click_prediction_small
  # - electricity
  # - estimation_of_obesity_levels
  # - Contaminant-detection-in-packaged-cocoa-hazelnut-spread-jars-using-Microwaves-Sensing-and-Machine-Learning-11.0GHz(Urbinati)
  # - Diamonds
  # - E-CommereShippingData
  # - FOREX_audjpy-day-High
  # - FOREX_audsgd-hour-High
  # - Fitness_Club_c
  - IEEE80211aa-GATS
  # - Intersectional-Bias-Assessment
  # - Job_Profitability
  # - Kaggle_bike_sharing_demand_challange
  # - Mobile_Price_Classification
  # - NHANES_age_prediction
  # - Shop_Customer_Data
  # - VulNoneVul
  # - Waterstress
  # - htru
  # - ibm-employee-performance
  # - internet_firewall
  # - jungle_chess_2pcs_raw_endgame_complete
  # - kc1
  # - led24
  # - okcupid_stem
  # - optdigits
  # - page-blocks
  # - pol
  # - pol_reg
  # - pole
  # - socmob
  # - splice
  # - archive_r56_Portuguese
  # - compass
  # - thyroid-dis
  # - wine
  # - yeast


transform_list:
  # ----------------------------------------------------------------
  # standard proprocess: nan, label
  - nan:
      policy: mean # mean, median
  - label: {}
  # ----------------------------------------------------------------
  # numerical encoding process
  # - num_cdf: 
  #     cdf_type: uniform # uniform, gaussian, dynamic
  #     cache_path: fit_cache
  #     n_components: 32
  #     binning_method: quantile # quantile, hdbscan, hierarchicalVkkk
  
  # ----------------------------------------------------------------
  # categorical encoding process
  # - cat_onehot: {}
  - cat_indice: {}
  # - cat_sincos: {}
  # - cat_targetindice: {}
  # - cat_target: {}
  # ----------------------------------------------------------------
  # normalization process
  # - norm: 
  #     policy: standard # none, standard, minmax, robust, power, quantile, maxabs

  # - norm:
  #     policy: standard

  # - uniple:
  #     n_bins: 1000000
  # - stretch:
  #     beta: 0.8
  - stretch_opt: 
      lambda_: 0.75

  # - num_cdf: 
  #     cdf_type: uniform # uniform, gaussian, dynamic
  #     cache_path: fit_cache
  #     n_components: 32
  #     binning_method: quantile # quantile, hdbscan, hierarchical


  - norm:
      policy: standard
  
  # - jointscale:
  #     scale_scheme: score
  #     min_scale: 0.0

  # - expand:
  #     K: 32


model_type: 
  # - ftt
  # - saint
  # - realmlp
  # - tabnet
  # - tabtransformer
  # - xgboost
  # - lightgbm
  - mlp
  - resnet
  # - mlp_plr
  # - realmlp
  # - xgboost
  # - catboost
  # - tabpfn
  # - PFN-v2
  # - tab

model_path: results_model/default_path
seed: 2025
seed_num: 15
gpu: 0
tune: true
tune_transform: true
tune_param: true
load_tune_config: true
n_trials: 10
